package com.jannirikshan.common.enums;

public enum NotificationType {
    CHALLENGE_SUBMITTED,
    CHALLENGE_APPROVED,
    CHALLENGE_REJECTED,
    CLARIFICATION_REQUESTED,
    CLARIFICATION_PROVIDED,
    UNIVERSITY_ASSIGNED,
    CHALLENGE_ACCEPTED,
    PROJECT_CREATED,
    TEAM_INVITATION,
    MILESTONE_ASSIGNED,
    MILESTONE_SUBMITTED,
    MILESTONE_APPROVED,
    MILESTONE_REJECTED,
    INDUSTRY_INTEREST,
    PARTNERSHIP_APPROVED,
    FUNDING_COMMITTED,
    PROJECT_STAGE_UPDATED,
    PROJECT_COMPLETED,
    GENERAL_ALERT
}
