spring.application.name=adhikar-backend

server.port=8080
server.error.include-message=always
server.error.include-binding-errors=always

# =====================================================
# DATABASE - PostgreSQL
# =====================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/adhikar_ai
spring.datasource.username=postgres
spring.datasource.password=kavish9090


# =====================================================
# JPA / HIBERNATE
# =====================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# =====================================================
# JWT
# =====================================================

jwt.secret=AdhikarAISecretKeyForJWT2026VeryLongAndSecure123456789
jwt.expiration=86400000


# =====================================================
# CLOUDINARY
# =====================================================

cloudinary.cloud-name=@hnuhmmfy
cloudinary.api-key=714817662769293
cloudinary.api-secret=0hQFoyA1bkgV8qdIOJt8DzT1M9o

# =====================================================
# AI SERVICE
# =====================================================

ai.service.url=http://127.0.0.1:8000
ai.service.connect-timeout=3s
ai.service.read-timeout=20s
